steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --region=$_FUNCTION_REGION
      - --source=.
      - --trigger-http
      - --runtime=$_FUNCTION_RUNTIME
      - --project=$_FUNCTION_PROJECT
      - --entry-point=$_ENTRY_POINT
    id: DEPLOY

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTION_NAME    : my-nodejs-app
  _FUNCTION_REGION  : northamerica-northeast1
  _FUNCTION_RUNTIME : nodejs22
  _FUNCTION_PROJECT : prod-451318
  _ENTRY_POINT      : helloworld
  
