steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_SERVICE_IMAGE', '.']
    id: BUILD

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_SERVICE_IMAGE']
    id: PUSH
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE
    id: DEPLOY

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_IMAGE   : us-central1-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
  _SERVICE_NAME    : hello
  _SERVICE_REGION  : us-central1
  _SERVICE_PROJECT : prod-451318
  _DOCKER_REGISTRY : denis-docker
  _DOCKER_IMAGENAME: mynginx-app
  
